settings:
  title: 'Status Page'
  url: 'https://status.maurom.dev' # used for Slack messages
  logo: icon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-webpage # unique identifier
    name: maurom.dev
    description: 'Main Webpage.' # default=empty
    url: 'https://maurom.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: transcript-system # unique identifier
    name: transcript.maurom.dev
    description: 'Overwatch Transcript System.' # default=empty
    url: 'https://transcript.maurom.dev/direct?link=https://cdn.discordapp.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: transcript-proxy-system # unique identifier
    name: proxy.maurom.dev
    description: 'Transcript System Proxy.' # default=empty
    url: 'https://transcript.maurom.dev/direct?link=https://cdn.discordapp.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: us1-node # unique identifier
    name: 'San Francisco Node #1'
    description: 'Node used for routing, proxying and other services.' # default=empty
    url: 'https://us1.maurom.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: us2-node # unique identifier
    name: 'California Node #1'
    description: 'Node used for proxying & redundancy and other services.' # default=empty
    url: 'https://us2.maurom.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

